[package]
name = "eller-macro"
version = "0.1.0"
authors = ["Fredrik Østrem <frx.apps@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.13"
syn = { version = "1.0.22", features = ["extra-traits"] }
quote = "1.0.5"
